wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716797800
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 23
      4: 3.12.3
      5: 0.17.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.001
