name: Model Training

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip git-lfs
        git lfs install
        pip install --upgrade pip
        pip install tensorflow numpy pandas matplotlib seaborn scikit-learn Pillow wandb jupyter


    - name: Log in to Weights & Biases
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: |
        wandb login --relogin $WANDB_API_KEY
    - name: Configure Git
      run: |
        git config --global user.email "aryantomukhlis@gmail.com"
        git config --global user.name "Mukhlis Aryanto"

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute trash_classification.ipynb --output executed_notebook.ipynb

    - name: Save Model to LFS
      run: |
        git add .gitattributes
        git add trash_classification_model.keras
        git commit -m "Add trash_classification_model.keras to Git LFS"
        git push origin main

    - name: Upload Model to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: model
        path: $HOME/model
