name: Model Training

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute trash_classification.ipynb --output executed_notebook.ipynb
    - name: Save Model
      run: |
        mkdir -p $HOME/model
        cp trash_classification_model.h5 $HOME/model
    - name: Upload Model to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: model
        path: $HOME/model
