name: Model Training

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install --upgrade pip
        pip install tensorflow numpy pandas matplotlib seaborn scikit-learn Pillow wandb jupyter

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute trash_classification.ipynb --output executed_notebook.ipynb

    - name: Save Model
      run: |
        mkdir -p $HOME/model
        cp trash_classification_model.h5 $HOME/model

    - name: Upload Model to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: model
        path: $HOME/model
